# Pull latest Debian bullseye
ARG ARCH=
FROM ${ARCH}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Update and install
RUN apt-get update && apt-get install -y \
 systemd \
 systemd-sysv \
 aptly \
 aptly-api \
 python3 \
 python3-requests \
 python3-debian \
 wget

# FIXME: Install aptly-intake manually until the new infra is up
RUN wget https://github.com/hybris-mobian-releng/aptly-intake/releases/download/hybris-mobian%2Fbullseye%2F2/aptly-intake_2+git20201004002357.3f200f6.bullseye.production_all.deb -O /tmp/aptly-intake.deb && dpkg -i /tmp/aptly-intake.deb ; apt-get -fy install

# Systemd configuration:
# Credits to Alexander Haase <ahaase@alexhaase.de>
#
# https://github.com/alehaa/docker-debian-systemd

# Configure systemd.
#
# For running systemd inside a Docker container, some additional tweaks are
# required. Some of them have already been applied above.
#
# The 'container' environment variable tells systemd that it's running inside a
# Docker container environment.
ENV container docker

# A different stop signal is required, so systemd will initiate a shutdown when
# running 'docker stop <container>'.
STOPSIGNAL SIGRTMIN+3

# The host's cgroup filesystem need's to be mounted (read-only) in the
# container. '/run', '/run/lock' and '/tmp' need to be tmpfs filesystems when
# running the container without 'CAP_SYS_ADMIN'.
#
# NOTE: For running Debian stretch, 'CAP_SYS_ADMIN' still needs to be added, as
#       stretch's version of systemd is not recent enough. Buster will run just
#       fine without 'CAP_SYS_ADMIN'.
VOLUME [ "/sys/fs/cgroup", "/run", "/run/lock", "/tmp" ]

# As this image should run systemd, the default command will be changed to start
# the init system. CMD will be preferred in favor of ENTRYPOINT, so one may
# override it when creating the container to e.g. to run a bash console instead.
CMD [ "/sbin/init" ]
