# Pull latest Debian bullseye
ARG ARCH=
FROM ${ARCH}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/bullseye/all/* /etc/apt/sources.list.d/
COPY repositories/bullseye/arm64/* /etc/apt/sources.list.d/

# Copy apt preferences
COPY preferences/bullseye/* /etc/apt/preferences.d/

COPY keyrings/all/* /etc/apt/lindroid-gpg.d/
COPY keyrings/arm64/* /etc/apt/lindroid-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Copy deployer for repo.lindroid.org
COPY extra/repo-lindroid-deploy.sh /usr/local/bin
COPY extra/repo-lindroid-sign.sh /usr/local/bin

# Add secondary architectures
RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf

# Update and install
RUN apt-get update && apt-get install -y --allow-downgrades \
 build-essential \
 devscripts \
 equivs \
 wget \
 openssh-client \
 curl \
 releng-tools \
 lindroid-apt-config \
 lindroid-archive-keyring && \
 apt-get dist-upgrade -y --allow-downgrades
