# Pull latest Debian bullseye
ARG ARCH=
FROM ${ARCH}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/all/* /etc/apt/sources.list.d/
COPY repositories/arm64/* /etc/apt/sources.list.d/

COPY keyrings/all/* /etc/apt/hybris-mobian-gpg.d/
COPY keyrings/arm64/* /etc/apt/hybris-mobian-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Copy deployer for repo.hybris-mobian.org
COPY extra/repo-hybris-mobian-deploy.sh /usr/local/bin

# Update and install
RUN apt-get update && apt-get install -y \
 build-essential \
 devscripts \
 equivs \
 wget \
 openssh-client \
 rsync \
 releng-tools \
 hybris-mobian-apt-config
