# Pull latest Debian bullseye
ARG ARCH=
FROM ${ARCH}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/all/* /etc/apt/sources.list.d/
COPY repositories/armhf/* /etc/apt/sources.list.d/

COPY keyrings/all/* /etc/apt/droidian-gpg.d/
COPY keyrings/armhf/* /etc/apt/droidian-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Copy deployer for repo.droidian.org
COPY extra/repo-droidian-deploy.sh /usr/local/bin
COPY extra/repo-droidian-sign.sh /usr/local/bin

# Add secondary architectures
RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf

# Update and install
RUN apt-get update && apt-get install -y --allow-downgrades \
 build-essential \
 devscripts \
 equivs \
 wget \
 openssh-client \
 rsync \
 releng-tools \
 droidian-apt-config \
 droidian-archive-keyring && apt-get dist-upgrade -y --allow-downgrades
