# Pull latest Debian bullseye
ARG ARCH=
FROM ${ARCH}/debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/all/* /etc/apt/sources.list.d/
COPY repositories/armhf/* /etc/apt/sources.list.d/

COPY keyrings/all/* /etc/apt/hybris-mobian-gpg.d/
COPY keyrings/armhf/* /etc/apt/hybris-mobian-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Update and install
RUN apt-get update && apt-get install -y \
 build-essential \
 devscripts \
 equivs \
 wget

# FIXME: Install releng-tools manually until the new infra is up
RUN wget https://github.com/hybris-mobian-releng/releng-tools/releases/download/hybris-mobian%2Fbullseye%2F6/releng-tools_6+git20201002213810.564c4e5.bullseye.production_all.deb -O /tmp/releng-tools.deb && dpkg -i /tmp/releng-tools.deb ; apt-get -fy install
