# Pull latest Droidian base image for flavour %(tag)s
ARG ARCH=
FROM quay.io/droidian/base:%(tag)s-%(arch)s

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/%(tag)s/all/* /etc/apt/sources.list.d/
COPY repositories/%(tag)s/%(arch)s/* /etc/apt/sources.list.d/

# Copy apt preferences
COPY preferences/%(tag)s/* /etc/apt/preferences.d/

COPY keyrings/all/* /etc/apt/droidian-gpg.d/
COPY keyrings/%(arch)s/* /etc/apt/droidian-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/

# Copy deployer for repo.droidian.org
COPY extra/repo-droidian-deploy.sh /usr/local/bin
COPY extra/repo-droidian-sign.sh /usr/local/bin

# Add secondary architectures
RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf

# Update and install
RUN apt-get update && apt-get install -y --allow-downgrades \
 build-essential \
 devscripts \
 equivs \
 wget \
 openssh-client \
 rsync \
 releng-tools && \
 apt-get dist-upgrade -y --allow-downgrades
